# Sets the URL name of the quickstart on public I/O (required)
slug: AzureAD

# Displayed in the UI (required)
title: Azure Active Directory

# Long-form description of the quickstart (required)
description: |
  This quickstart allows for basic data collection about information related to the Azure Active Directory services.

# Displayed in search results and recommendations. Summarizes a quickstarts functionality.
summary: |
  Basic data collection about Azure Active Directory.

# Support level: New Relic | Verified | Community (required)
level: Community

# Authors of the quickstart (required)
authors:
  - Liz Huller
  - Will Foster
  - Jonathan Chu
  - Daphne Hong
  - Hala Rawas
  - Momo Siu

# Keywords for filtering / searching criteria in the UI
keywords:
  - azure
  - active directory
  - azure ad

# Reference to install plans located under /install directory
# Allows us to construct reusable "install plans" and just use their ID in the quickstart config
installPlans:
  - example-install
alerts:
  - condition-a
  - condition-b
dashboards:
  - dashboard-1
  - dashboard-2
# Documentation references
documentation:
  - name: Installation docs
    url: docs.newrelic.com
    description: Description about this doc reference

# Content / Design
icon: logo.svg
website: https://www.newrelic.com
